#Put your environment variables into .env!

services:
  novabot-core:
    build: novabot-core
    hostname: novabot
    volumes:
      - ${novabot_local_resources}:${novabot_resources}
    environment:
      discord_token: ${discord_token}
      novabot_resources: ${novabot_resources}
      novabot_prefix: ${novabot_prefix}
      nova_phone_number: ${nova_phone_number}
      twilio_token: ${twilio_token}
      twilio_sid: ${twilio_sid}
  