name: Build NovaBot

on: push

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}
  novabot_resources: /usr/src/app/novabot-resources
  novabot_local_resources: /NovaBot
  novabot_prefix: nd!

jobs:
  runbot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          touch .env
          echo discord_token=${{ secrets.DISCORD_TOKEN }} >> .env
          echo nova_phone_number=${{ secrets.NOVA_PHONE_NUMBER }} >> .env
          echo twilio_token=${{ secrets.TWILIO_TOKEN }} >> .env
          echo twilio_sid=${{ secrets.TWILIO_SID }} >> .env
          echo novabot_resources=/usr/src/app/novabot-resources >> .env
          echo novabot_local_resources=/NovaBot >> .env
          echo novabot_prefix=nd! >> .env
          echo azure_connection_string=${{ secrets.AZURE_CONNECTION_STRING }} >> .env
          echo cdn_location=${{ secrets.CDN_LOCATION }} >> .env
          echo blob_container=${{ secrets.BLOB_CONTAINER }} >> .env
          sudo docker-compose up -d --build