name: Build NovaBot

on: push

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}
  novabot_resources: /usr/src/app/novabot-resources
  novabot_local_resources: /NovaBot
  novabot_prefix: nd!

jobs:
  runbot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: | 
        touch .env
        echo discord_token=${{ secrets.DISCORD_TOKEN }} >> .env
        echo novabot_resources=/usr/src/app/novabot-resources >> .env
        echo novabot_local_resources=/NovaBot >> .env
        echo novabot_prefix=nd! >> .env
        sudo docker-compose up -d --build